# File: netlify.toml
# Konfigurasi yang lebih sederhana

[build]
  # Folder tempat Netlify akan menemukan function Anda.
  functions = "netlify/functions/"
  # Folder yang akan di-publish.
  publish = "."
